version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    links:
    - flask-app
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    restart: always
  flask-app:
    build: ./flask-app
    environment:
    - db_connection=mysql+pymysql://root:password@database:3306/finalproject
    - PYTHONUNBUFFERED=1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 1
    depends_on:
    - database
    restart: always
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: finalproject
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
    - published: 3306
      target: 3306
    # volumes:
    # - mysql-data:/var/lib/mysql
    # restart: always