version: "3.8"
services:
  nginx:
    image: nginx:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  flask-app:
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306
    volumes:
    - ./db:/docker-entrypoint-initdb.d